name: Process and Push Blacklist Data

on:
  push:
    branches:
      - main

jobs:
  process-blacklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run remove_qq_dup.py
        run: python remove_qq_dup.py

      - name: Run txt2json.py
        run: python txt2json.py

      - name: Run txt2db.py
        run: python txt2db.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update blacklist data after push'
          git push origin main
